### ISSUE TITLE
motan-openresty如何安装

### ISSUE THREAD

**Issue by mogu1986** [weibocom/motan-openresty#2]
motan-openresty的安装文档太过简洁，根据文档完全跑不起来。能否像JAVA版那样提供比较详细的说明文档。

**Comment by idevz** [comment]
感谢关注，我接下来再整理个更细致的，部署其实很简单，你现在自己可以先：clone 代码后，在 Nginx 主配置中将代码路径加到 `lua_package_path` 下面，然后在把 `exapmle` 路径下的实例配置 include 到主配置中即可。

**Comment by mogu1986** [comment]
是的，openresty的都是基于这种方式安装，和同事试验多次无解。 我整理了一下操作记录，是哪步有错吗？

1. 安装目录：
cd /opt && git clone https://github.com/weibocom/motan-openresty.git

2. nginx.conf 
	2.1 http部分 加入
		init_by_lua_block {
			motan = require "motan"
			local sys_conf = {
				MOTAN_CLIENT_CONF_FILE = "MOTAN_CLIENT_CONF",
				MOTAN_SERVER_CONF_FILE = "MOTAN_SERVER_CONF",
				MOTAN_LUA_SERVICE_PERFIX = "com.weibo.motan.",
				SERVICE_PATH = "/opt/motan/examples/motan-service",
			}
			motan.init(sys_conf)
		}

		init_worker_by_lua_block {
			motan.init_worker_motan_client()
		}
	2.2 加入include
	include /opt/motan/examples/ngx_conf/orcon.conf;	
	

3. 修改orcon.conf
	lua_shared_dict motan_client 20m;
	lua_package_path "/opt/motan/?.lua;;";
	lua_package_cpath "/opt/motan/libs/?.so;;";
	server {
		listen 9880;
		lua_code_cache on;
		access_by_lua_block {
			motan.access()
		}

		location / {
			content_by_lua_block {
				motan.content_motan_client_test()
			}
		}
	}


启动命令：
/usr/local/openresty/nginx/sbin/nginx -c /opt/motan/examples/ngx_conf/nginx.conf

**Comment by idevz** [comment]
nginx.conf 主配置文件中 HTTP 段添加的配置是用来测试 Motan-OpenResty 的 Lua Client，还需要在 Stream 段添加 Server 端的配置，可以参考这个 [例子](https://github.com/motan-ecosystem/motan-examples/blob/cb31c261d17d34e611f8ba91649265c7cfcd52aa/openresty-lua/motan-openresty.conf#L55)

**Comment by sgpf** [comment]
lua_package_path "/opt/motan/?.lua;/opt/motan/?/init.lua;;";
@mogu1986 看他代码 需要增加init
